"use client";

import { useState, useCallback, useEffect } from "react";
import Link from "next/link";
import { Badge, Avatar, Sparkline, Modal, progressColor, DatePicker, Toast } from "@/components";
import { CLIENTS, PROJECTS, ACTIVITIES, INVOICES, REV, getClient } from "@/mock-data";
import { createProject, getUserClients } from "@/app/actions";

const dotColor = (t: string) => t === "success" ? "bg-emerald-400" : t === "warning" ? "bg-amber-400" : t === "danger" ? "bg-red-400" : "bg-f-accent";

function exportDashboardPDF() {
  const win = window.open("", "_blank");
  if (!win) return;
  const stats = [
    { l: "Active Projects", v: "8" }, { l: "Total Clients", v: "12" },
    { l: "Revenue (Mar)", v: "$8,420" }, { l: "Outstanding", v: "$2,150" },
  ];
  const projectRows = PROJECTS.map(p => {
    const cl = getClient(p.clientId);
    return `<tr><td style="padding:10px 12px;border-bottom:1px solid #eee;font-weight:600">${p.title}</td><td style="padding:10px 12px;border-bottom:1px solid #eee">${cl.company}</td><td style="padding:10px 12px;border-bottom:1px solid #eee">${p.status}</td><td style="padding:10px 12px;border-bottom:1px solid #eee">${p.progress}%</td><td style="padding:10px 12px;border-bottom:1px solid #eee">${p.due}</td></tr>`;
  }).join("");
  const invoiceRows = INVOICES.map(inv => {
    const cl = getClient(inv.cid);
    return `<tr><td style="padding:10px 12px;border-bottom:1px solid #eee">${cl.company}</td><td style="padding:10px 12px;border-bottom:1px solid #eee">${inv.num}</td><td style="padding:10px 12px;border-bottom:1px solid #eee;font-weight:600">${inv.amt}</td><td style="padding:10px 12px;border-bottom:1px solid #eee">${inv.status}</td></tr>`;
  }).join("");
  win.document.write(`<!DOCTYPE html><html><head><title>Folio Dashboard Report</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,system-ui,sans-serif;color:#1a1a1a;padding:40px;max-width:800px;margin:0 auto}h1{font-size:28px;font-weight:700;margin-bottom:4px}h2{font-size:18px;font-weight:700;margin:32px 0 16px;padding-bottom:8px;border-bottom:2px solid #6C5CE7}.meta{color:#666;font-size:13px;margin-bottom:32px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:8px}.stat{background:#f8f8f6;border-radius:12px;padding:16px}.stat-label{font-size:11px;color:#888;font-weight:600;text-transform:uppercase;letter-spacing:0.5px}.stat-value{font-size:28px;font-weight:700;margin-top:4px}table{width:100%;border-collapse:collapse;font-size:13px}th{text-align:left;padding:10px 12px;border-bottom:2px solid #ddd;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;color:#888}.footer{margin-top:48px;padding-top:16px;border-top:1px solid #eee;text-align:center;font-size:11px;color:#aaa}@media print{body{padding:20px}}</style></head><body><h1>Dashboard Report</h1><p class="meta">Generated ${new Date().toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</p><div class="stats">${stats.map(s=>`<div class="stat"><div class="stat-label">${s.l}</div><div class="stat-value">${s.v}</div></div>`).join("")}</div><h2>Active Projects</h2><table><thead><tr><th>Project</th><th>Client</th><th>Status</th><th>Progress</th><th>Due</th></tr></thead><tbody>${projectRows}</tbody></table><h2>Recent Invoices</h2><table><thead><tr><th>Client</th><th>Invoice</th><th>Amount</th><th>Status</th></tr></thead><tbody>${invoiceRows}</tbody></table><div class="footer">Generated by Folio · ${new Date().toLocaleString()}</div><script>window.onload=()=>{window.print()}</script></body></html>`);
  win.document.close();
}

export default function DashboardView() {
  const [modal, setModal] = useState(false);
  const [toast, setToast] = useState({ show: false, message: "", type: "success" as "success" | "error" });
  const showToast = useCallback((message: string, type: "success" | "error" = "success") => {
    setToast({ show: true, message, type });
  }, []);

  return (
    <>
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <p className="text-sm text-f-muted font-medium mb-1">Good afternoon</p>
          <h1 className="text-2xl sm:text-3xl font-bold text-f-text tracking-tight font-display">Dashboard</h1>
        </div>
        <div className="flex gap-2.5">
          <button onClick={exportDashboardPDF} className="px-4 py-2.5 rounded-lg text-sm font-semibold text-f-muted border border-f-border hover:border-f-muted hover:text-f-text transition-all flex items-center gap-2">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" /></svg>
            Export
          </button>
          <button onClick={() => setModal(true)} className="px-4 py-2.5 rounded-lg text-sm font-semibold text-white bg-f-accent shadow-lg shadow-f-accent/25 hover:-translate-y-0.5 transition-all flex items-center gap-2">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 5v14M5 12h14" /></svg>
            New Project
          </button>
        </div>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 mb-8">
        {[
          { l: "Active Projects", v: "8", s: "↑ 2 this month", up: true },
          { l: "Total Clients", v: "12", s: "↑ 3 this quarter", up: true },
          { l: "Revenue (Mar)", v: "$8,420", s: "↑ 18% vs Feb", up: true, chart: true },
          { l: "Outstanding", v: "$2,150", s: "2 overdue", up: false },
        ].map((s, i) => (
          <div key={i} className="bg-f-surface border border-f-border rounded-xl p-4 sm:p-5 hover:border-[#3A3A48] hover:-translate-y-0.5 transition-all">
            <div className="flex items-start justify-between">
              <div>
                <p className="text-[11px] text-f-muted font-medium mb-1.5">{s.l}</p>
                <p className="text-2xl sm:text-3xl font-bold text-f-text tracking-tight">{s.v}</p>
                <p className={`text-[11px] font-semibold mt-1 ${s.up ? "text-emerald-400" : "text-red-400"}`}>{s.s}</p>
              </div>
              {s.chart && <div className="hidden sm:block opacity-70 mt-1"><Sparkline data={REV} /></div>}
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-[1fr_380px] gap-6">
        <div className="bg-f-surface border border-f-border rounded-xl overflow-hidden">
          <div className="px-4 sm:px-6 py-4 flex items-center justify-between border-b border-f-border">
            <h2 className="text-base font-bold text-f-text">Active Projects</h2>
          </div>
          <div className="divide-y divide-f-border/50">
            {PROJECTS.map(p => { const cl = getClient(p.clientId); return (
              <Link key={p.id} href={`/project/${p.id}`} className="px-4 sm:px-6 py-3.5 flex items-center gap-3 sm:gap-4 hover:bg-f-hover cursor-pointer transition-colors">
                <Avatar text={cl.avatar} color={cl.color} />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-f-text truncate">{p.title}</p>
                  <p className="text-xs text-f-muted">{cl.company}</p>
                </div>
                <Badge status={p.status} />
                <div className="hidden sm:flex items-center gap-2">
                  <div className="w-20 h-1.5 rounded-full bg-white/[0.06] overflow-hidden">
                    <div className="h-full rounded-full" style={{ width: `${p.progress}%`, background: progressColor(p.status) }} />
                  </div>
                  <span className="text-xs text-f-muted tabular-nums w-8 text-right">{p.progress}%</span>
                </div>
                <span className={`hidden sm:inline text-sm ${p.status === "OVERDUE" ? "text-red-400" : "text-f-muted"}`}>{p.due}</span>
              </Link>
            ); })}
          </div>
        </div>

        <div className="flex flex-col gap-6">
          <div className="bg-f-surface border border-f-border rounded-xl overflow-hidden">
            <div className="px-4 sm:px-6 py-4 border-b border-f-border"><h2 className="text-base font-bold text-f-text">Activity</h2></div>
            <div className="divide-y divide-f-border/50">
              {ACTIVITIES.map(a => (
                <div key={a.id} className="px-4 sm:px-6 py-3.5 flex gap-3 items-start hover:bg-f-hover transition-colors">
                  <div className={`w-2 h-2 rounded-full mt-1.5 shrink-0 ${dotColor(a.type)}`} />
                  <div>
                    <p className="text-sm text-f-text leading-relaxed"><span className="font-semibold">{a.actor}</span> {a.action}</p>
                    <p className="text-[11px] text-f-muted mt-0.5">{a.time}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="bg-f-surface border border-f-border rounded-xl overflow-hidden">
            <div className="px-4 sm:px-6 py-4 border-b border-f-border"><h2 className="text-base font-bold text-f-text">Recent Invoices</h2></div>
            <div className="divide-y divide-f-border/50">
              {INVOICES.map(inv => { const cl = getClient(inv.cid); return (
                <div key={inv.id} className="px-4 sm:px-6 py-3.5 flex items-center justify-between hover:bg-f-hover transition-colors">
                  <div><p className="text-sm font-semibold text-f-text">{cl.company}</p><p className="text-xs text-f-muted">{inv.num} · {inv.date}</p></div>
                  <div className="text-right"><p className="text-sm font-bold text-f-text">{inv.amt}</p><Badge status={inv.status} /></div>
                </div>
              ); })}
            </div>
          </div>
        </div>
      </div>

      <Modal open={modal} onClose={() => setModal(false)} title="New Project">
        <NewProjectForm onClose={() => setModal(false)} onSuccess={(title) => showToast(`Project "${title}" created successfully`)} />
      </Modal>

      <Toast message={toast.message} type={toast.type} show={toast.show} onClose={() => setToast(t => ({ ...t, show: false }))} />
    </>
  );
}

function NewProjectForm({ onClose, onSuccess }: { onClose: () => void; onSuccess: (title: string) => void }) {
  const [title, setTitle] = useState("");
  const [clientId, setClientId] = useState("");
  const [description, setDescription] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [dbClients, setDbClients] = useState<Array<{ id: string; name: string; company: string | null }>>([]);
  const [loadingClients, setLoadingClients] = useState(true);

  useEffect(() => {
    getUserClients().then(clients => {
      setDbClients(clients);
      setLoadingClients(false);
    }).catch(() => setLoadingClients(false));
  }, []);

  const handleSubmit = async () => {
    setSaving(true);
    setError("");
    try {
      const result = await createProject({ title, clientId, description: description || undefined, dueDate: dueDate || undefined });
      onClose();
      onSuccess(result.title);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to create project");
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <div className="p-6 space-y-4">
        {error && <div className="px-4 py-2.5 rounded-lg bg-red-500/10 border border-red-500/20 text-sm text-red-400">{error}</div>}
        <div>
          <label className="block text-xs font-semibold text-f-muted mb-1.5">Project Name</label>
          <input value={title} onChange={e => setTitle(e.target.value)} className="w-full px-4 py-2.5 rounded-lg bg-f-bg border border-f-border text-sm text-f-text placeholder-[#555] focus:border-f-accent focus:outline-none" placeholder="e.g. Brand Refresh" />
        </div>
        <div>
          <label className="block text-xs font-semibold text-f-muted mb-1.5">Client</label>
          <select value={clientId} onChange={e => setClientId(e.target.value)} className="w-full px-4 py-2.5 rounded-lg bg-f-bg border border-f-border text-sm text-f-text focus:border-f-accent focus:outline-none appearance-none">
            <option value="">{loadingClients ? "Loading clients..." : dbClients.length === 0 ? "No clients — add one first" : "Select a client..."}</option>
            {dbClients.map(c => <option key={c.id} value={c.id}>{c.company || c.name}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-xs font-semibold text-f-muted mb-1.5">Description</label>
          <textarea value={description} onChange={e => setDescription(e.target.value)} rows={3} className="w-full px-4 py-2.5 rounded-lg bg-f-bg border border-f-border text-sm text-f-text placeholder-[#555] focus:border-f-accent focus:outline-none resize-none" placeholder="Brief project description..." />
        </div>
        <div>
          <label className="block text-xs font-semibold text-f-muted mb-1.5">Due Date</label>
          <DatePicker value={dueDate} onChange={setDueDate} placeholder="Select due date" />
        </div>
      </div>
      <div className="px-6 py-4 border-t border-f-border flex gap-3 justify-end">
        <button onClick={onClose} className="px-4 py-2.5 rounded-lg text-sm font-semibold text-f-muted border border-f-border hover:text-f-text transition-all">Cancel</button>
        <button onClick={handleSubmit} disabled={!title || !clientId || saving} className="px-5 py-2.5 rounded-lg text-sm font-bold text-white bg-f-accent shadow-lg shadow-f-accent/25 transition-all disabled:opacity-40 disabled:cursor-not-allowed">
          {saving ? "Creating..." : "Create Project"}
        </button>
      </div>
    </>
  );
}
